### ISSUE TITLE
Prototype Roadmap

### ISSUE THREAD

**Issue by tdurand** [opendatacam/opendatacam#18]
Prototype Up to date URL: https://traffic-cam-yxqtypoqyv.now.sh/game

@mmmmmmmmmmmmmmmm  tasks:

- [x] Share the current sketch file on google drive
- [x] Upload a good variety of possible (_crops / inclination, maybe consult @b-g for ideas of footage_) on the vimeo account (saying 10 diff crops) and share the detections file associated on the google drive (with maybe the vimeo id of something to identify what belong to what). Maybe stick to 5 min of footage / video, and also do the **all the detections with the same resolution** (1920x1080 to have more pixel for better detections results). If we try having "portrait" videos, it will obviouly be a different resolution, but in that case specify which.
- [ ] Find some sound tracks that could be nice
- [x] Continue exploring games / mode ideas that we could integrate in the prototype. Maybe do some more prototypes of ideas.
- [x] Follow along the implem of the prototype and ask questions on what isn't clear 😉 
- [x] Anything I didn't think about 

@tdurand tasks 

Work on the implementation of the prototype (react app)

- [x] Implement the Beat the traffic game in the react app under the with the svg masking implem
- [ ] Improve the beat the traffic game with some ideas of @mmmmmmmmmmmmmmmm (sound tracks, counting cars..) , @b-g (sprite animation, blur edges...), try to have different options of disappearing cars / game mode under different urls to test
- [x] Include some of the design elements of @mmmmmmmmmmmmmmmm  for the UI 
- [x] Add a select to be able to switch betweens video
- [x] Make sure it works correctly on mobile / desktop
- [x] Upload the prototype on some public url to be able to share it with people

@b-g tasks

Provide assistance on demand 😉 +

- [x] @tdurand will try to have a first prototype done by wednesday, do a first review to add / remove stuff to it.

 
BTW, I'll be off on monday but back on tuesday.
