### ISSUE TITLE
Update to NodeJS v20

### ISSUE THREAD

**Issue by vsaw** [opendatacam/opendatacam#602]
## Goal

Remove NodeJS 12, which is obsolete and outdated, and switch to the current NodeJS 20 (LTS)

## TODOs

- [x] Fix Runtime error (see below)
- [x] Remove NodeJS 12 from Darknet base
- [x] Install Node 20 in ODC container
- [x] Update CI/CD tests to use Node 18 and 20

## Background Info

Most likely due to OpenDataCam/NextJs being out of date. The error I get when starting is:

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/vsaw/Documents/Development/opendatacam/opendatacam/node_modules/next/dist/compiled/webpack/bundle5.js:133790:18)
    at BulkUpdateDecorator.update (/Users/vsaw/Documents/Development/opendatacam/opendatacam/node_modules/next/dist/compiled/webpack/bundle5.js:133692:50)
    at /Users/vsaw/Documents/Development/opendatacam/opendatacam/node_modules/next/dist/compiled/webpack/bundle5.js:56905:9
    at /Users/vsaw/Documents/Development/opendatacam/opendatacam/node_modules/next/dist/compiled/webpack/bundle5.js:29533:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

Workaround: Use `NODE_OPTIONS=--openssl-legacy-provider` e.g.

```
NODE_OPTIONS=--openssl-legacy-provider npm run dev
```

**Comment by vsaw** [comment]
I tried updating NextJS but that didn't work because of https://stackoverflow.com/questions/73761243/you-are-using-legacy-implementaion-please-update-your-code-use-createwrapper

Will try again tomorrow by setting NODE_OPTIONS.
